export const API_URL = {
  login: "identity/auth/login",
  register: "identity/auth/register-new-user",
  forgotPassword: "identity/auth/forgot-password",
  verifyRegisterOtp: "identity/auth/verify-login-otp",
  verifySignInOtp: "identity/auth/verify-password-otp",
  reSendOtpRegister: "identity/auth/forgot-register-user-password",
  reSendOtpSignIn: "identity/auth/forgot-password",
  resetPassword: "identity/auth/reset-password",
  getAllRole: "core/roles/all-role",
  getUserRole: "core/user-roles-mapping/get-user-permission",
  addAdmin: "core/user/add-user-admin",
  activeInactiveUser: "core/user/act-deactivate",
  getAllPlayer: "core/user/all-player-user",
  getAllCourseAdmin: "core/user/all-course-admin",
  getAllSuperAdmin: "core/user/all-super-admin",
  getAllCount: "core/user/get-all-user-count",
  getCourseList: "core/course/courses",
  getCourseData: "core/club/all-club",
  getHoleByCourseId: "core/hole/hole-by-courseId",
  qrCodeByCourseId: "https://dev.acecamgolf.com/contests?course=",
  qrCodeByHoldId: " https://dev.acecamgolf.com/contests",
  fbRedirectUI: "http://localhost:8080/aceCamDev/abcd",
  verigyGoogleToken: "identity/auth/verifyGoogleToken",
  verifyFbToken: "identity/auth/verifyFacebookToken",
  getAllContests: "core/contest/all",
  updateStatusContest: "core/contest/update-status",
  uploadProfileImage: "core/user/update-profile-pic",
  fetchUserProfile: "core/user/fetch-profile",
  updateUserProfile: "core/user/update-profile",
  downloadProfileImage: "core/files/view-file",
  searchPlayer: "core/user/all-player-user",
  getClubCourseAdmin: "core/user-course-club/course-admins",
  getCourseAdminByClubId: "/core/user-course-club/course-admins-count",
  createContest: "/core/contest/create",
  getContestById: "/core/contest/getContestById",
  getCourses: "/core/course/courses",
  getHolesByCourseId: "/core/hole/hole-by-courseId-without-tee",
  getTeeByHoleId: "/core/tee/tee-by-holeId",
  getContestByTeeId: "/core/contest/get-daily-active-contest",
  getAllPlayerReqHighlights: "/core/record/player-request-highlight",
  requestHighlight: '/core/request-video/create',
  getAllApprovedVideos: '/core/request-video/all-approved-req-videos',
  getAllPublishedVideos: '/core/request-video/all-published-videos',
  getAllShotOfTheWeek: "/core/shot-of-the-week/all-shot-of-the-week",
  getAllWinnersVideo:'/core/winner-video/all-winner-videos',
  getAllReqVideos: '/core/request-video/all-req-videos',
  updateVideoStatus: "/core/request-video/update-status",
  uploadRequestedVideo: "/core/video/upload",
  publishVideos: "/core/request-video/published",
  deleteVideo: "/core/video/delete",
  uploadShotOfTheWeek: "/core/shot-of-the-week/create",
  contestCheckoutCoreRegistrationSave: "/core/registration/save",
  getCourseSpecificVideo:"/core/winner-video/get-course-specific-video",
  getAllHighlightsCounts: "/core/request-video/get-all-highlight-count",
  getAllMediaCounts:"/core/request-video/get-all-media-count"
};
