export const ROUTES = {
  // HOME: "/",
  LOGIN: "/",
  SIGNUP: "/signup",
  FORGET_PASSWORD: "/forget-password",
  DASHBOARD: "/dashboard",
  STRIPE: "/stripe",
  RESET_PASSWORD: "/reset-password",
  CONTESTS: "/contests",
  CREATE_CONTEST: "/create-contest",
  UPDFATE_CONTEST: "/update-contest/:id",
  PROFILE: "/profile",
  GENERATE_QR: "/generate-qr",
  CONTEST_LIST: "/contest-list",
  CHECKOUT: "/checkout",
  COMMUNITY: "/community",
  MEDIA: "/media-management",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  USERS: '/users'
};
