name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)
trigger:
  batch: true
  branches:
    include:
      - test
      - feature/*
    exclude:
      - main

variables:
  major: 1
  minor: 0
  patch: $[counter(variables['minor'], 1)]
  tag: $(major).$(minor).$(patch)
  acr_server: "acecam.azurecr.io"
  resource_group: rg-acecam
  aks_resource_name: acecam-aks-prod-001
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    env: prd
  ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/test') }}:
    env: test
  ${{ else }}:
    env: dev
# ${{ elseif startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
pool: "aks-deployer"
stages:
  - stage: build_publish_package
    condition: ne(variables['env'], '')
    displayName: Build and Publish package
    jobs:
      - job: Build
        steps:
          - task: Npm@1
            inputs:
              command: "install"
              workingDir: "source_code"
          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: "source_code"
              customCommand: "run build"
          - publish: $(Build.SourcesDirectory)/source_code/build
            artifact: $(Build.Repository.Name)
            displayName: Publish Artifact
