export const validationConstant = {
    firstNameRequired: "First Name is required.",
    firstNameContains: "First Name must contain only alphabetic characters.",
    firstNameMaxLength: "First Name must be less than 25 characters.",
    lastNameRequired: "Last Name is required.",
    lastNameContains: "Last Name must contain only alphabetic characters.",
    lastNameMaxLength: "Last Name must be less than 25 characters.",
    usernameRequired: "Username is required.",
    usernameMinWordLimit: "Username must be at least 3 characters.",
    userNameMaxWordLimit: "Username must be less than 25 characters.",
    userNameContains:"Username must contain only alphanumeric characters.",
    phoneNumberIsRequired: "Phone is required.",
    phoneNumberContains: "Phone number must only contain numbers.",
    validPhone: "Please enter valid phone number.",
    countryCodeRequired: "Country code is required.",
    countryCodeMaxLength: "Country code must be less than 4 numbers.",
    confirmPasswordRequired: "Confirm password is required.",
    matchingConfirmPassword: "The passwords do not match. Please ensure both password fields are identical.",
    validEmail: "Please enter a valid email address.",
    emailRequired: "Email is required.",
    agreeTermsAndConditions: "You must agree to the Terms and Conditions to proceed.",
    validDateFormate: "Invalid date. Expected format: MM/DD/YYYY",
    DOBCanNotBeInFuture: "Date cannot be in the future.",
    passWordMatching: "The passwords do not match. Please ensure both password fields are identical.",
    passwordIsRequired: "Password is required.",
    passwordContains: "Password must be 8-25 characters long, include at least one letter, one number, and one special character.",
    videoRejestReason: "Reject Reason is required.",
    videoRejestReasonMaxLength: "Reject Reason must be less than 100 characters.",
    videoTitleReq: "Video title is required.",
    videoTitleMaxLength: "Video title must be less than 25 characters.",
    videoDiscriptionReq: "Video description is required.",
    discriptionForReq:"Description is required.",
    videoDiscriptionMaxLength: "Video description must be less than 100 characters.",
    clubMustbeSelected: "Club must be selected.",
    courseMustbeSelect: "Course must be selected.",
    holeMustbeSelected: "Hole must be selected.",
    teeMustbeSelected :"Tee must be selected.",
    contestNameMustbeSelected: "Contest Type must be selected.",
    dateTimeMustBeSelected: "Date and Time must be selected",
    locationContains: "Location must contain only alphabetic characters.",
    cityContains: "City must contain only alphabetic characters.",
    invalidGHIN: "Invalid GHIN Number.",
    handicapNumberContains: "Handicap number Must be a number.",
    validHandiCapNumber: "Handicap must be a valid number.",
    handicapNumberReq: "Handicap number is required.",
    mandatoryField: "This field is mandatory.",
    startDateCannotBeLaterThenEnddate: "Start date cannot be later than end date.",
    endDateMustBeLaterThenStartDate: "End date must be later than start date.",
    activeHourStartTimeCanNotbeLaterThenActivehourEndTime:"Active hours start time cannot be later than active hours end time. Please select a valid time range.",
    activeHourEndTimeCanNotBeEarlierThenActiveHourStartTime: "Active hours end time cannot be earlier than the active hours start time. Please select a valid time range.",
    registrationStartTImeShouldBeEarlierThenActivehourStartTime: "Registration start time should be earlier than active hours start time.",
    registrationStartTimeCanNotBeLaterThenRegistrationEndTime: "Registration start time cannot be later than registration end time. Please select a valid time range.",
    registrationEndTimeMustBeATLeast30MinBeforeContestActivehourEndTime:"Registration end time must be at least 30 minutes before the Contest active hours end time.",
    registrationEndTimeCannotBeEarlierThentheStartTime: "Registration end time cannot be earlier than the start time. Please select a valid time range.",
    valueShouldBeBetweet5and100: "Value should be between 5 and 100",
    percentageMustBeatLeast0:"Percentage must be at least 0.",
    percentageCannotExceed100:"Percentage cannot exceed 100.",
    validNumberValue: "Please enter a valid number.",
    totalPayOutStructureSHouldBe100: "Total Payout percentage should be 100%.",
    entriesPer24HoursShouldNotBeLessThan1: "Entries Per 24 hours should not be less than 1.",
    startDateCanNotBeEarlierThanTodaysDate: "Start date cannot be earlier than today's date. Please select a valid date.",
    courseRequired: "Course is required"
}